export const SELECTED_USER_DATA = 'SELECTED_USER_DATA';

export const SELECTED_USER_CAR_REQUEST = 'SELECTED_USER_CAR_REQUEST';
export const SELECTED_USER_CAR_SUCCESS = 'SELECTED_USER_CAR_SUCCESS';
export const SELECTED_USER_CAR_FAIL = 'SELECTED_USER_CAR_FAIL';


export const ALL_BOOKING_REQUEST_DATA_REQUEST = 'ALL_BOOKING_REQUEST_DATA_REQUEST';
export const ALL_BOOKING_REQUEST_DATA_SUCCESS = 'ALL_BOOKING_REQUEST_DATA_SUCCESS';
export const ALL_BOOKING_REQUEST_DATA_FAIL = 'ALL_BOOKING_REQUEST_DATA_FAIL';

export const EDIT_USER_DATA = 'EDIT_USER_DATA';