export const BIDING_DETAIL_SUCCESS = 'BIDING_DETAIL_SUCCESS';

export const BIDDING_DETAIL_BY_USER_ID_REQUEST = 'BIDDING_DETAIL_BY_USER_ID_REQUEST';
export const BIDDING_DETAIL_BY_USER_ID_SUCCESS = 'BIDDING_DETAIL_BY_USER_ID_SUCCESS';
export const BIDDING_DETAIL_BY_USER_ID_FAIL = 'BIDDING_DETAIL_BY_USER_ID_FAIL';

export const BIDDING_DETAIL_BY_BOOKING_ID_REQUEST = 'BIDDING_DETAIL_BY_BOOKING_ID_REQUEST';
export const BIDDING_DETAIL_BY_BOOKING_ID_SUCCESS = 'BIDDING_DETAIL_BY_BOOKING_ID_SUCCESS';
export const BIDDING_DETAIL_BY_BOOKING_ID_FAIL = 'BIDDING_DETAIL_BY_BOOKING_ID_FAIL';