export const BOOKING_DETAIL_REQUEST = 'BOOKING_DETAIL_REQUEST';
export const BOOKING_DETAIL_SUCCESS = 'BOOKING_DETAIL_SUCCESS';
export const BOOKING_DETAIL_FAIL = 'BOOKING_DETAIL_FAIL';


export const BIDING_DETAIL_SUCCESS = 'BIDING_DETAIL_SUCCESS';