export const BOOKING_DETAIL_REQUEST = 'BOOKING_DETAIL_REQUEST';
export const BOOKING_DETAIL_SUCCESS = 'BOOKING_DETAIL_SUCCESS';
export const BOOKING_DETAIL_FAIL = 'BOOKING_DETAIL_FAIL';

export const BOOKING_DATA_FILTER = 'BOOKING_DATA_FILTER';

export const UPDATE_CAR_DATA = 'UPDATE_CAR_DATA';


