export const USER_SIGNIN_REQUEST = 'USER_SIGNIN_REQUEST';
export const USER_SIGNIN_SUCCESS = 'USER_SIGNIN_SUCCESS';
export const USER_SIGNIN_FAIL = 'USER_SIGNIN_FAIL';
export const USER_SIGNOUT = 'USER_SIGNOUT';

export const ALL_USER_DATA_REQUEST = 'ALL_USER_DATA_REQUEST';
export const ALL_USER_DATA_SUCCESS = 'ALL_USER_DATA_SUCCESS';
export const ALL_USER_DATA_FAIL = 'ALL_USER_DATA_FAIL';

export const USER_CAR_REQUEST = 'USER_CAR_REQUEST';
export const USER_CAR_SUCCESS = 'USER_CAR_SUCCESS';
export const USER_CAR_FAIL = 'USER_CAR_FAIL';